#include "ui.h"
#include <lvgl.h>
#include <string.h>

// ── Grid constants ────────────────────────────────────────────────────────────
// departure_mono_upper_28: line_height=25px, adv_w=285/16≈18px per char
#define GRID_COLS  12
#define GRID_ROWS   8
#define CHAR_H     25   // font line_height in px
#define CHAR_W     18   // font advance width in px (285 / 16, rounded)

// Center the grid box within the 280×240 display
#define BOX_X  ((TFT_WIDTH  - GRID_COLS * CHAR_W) / 2)   // ~32px left margin
#define BOX_Y  ((TFT_HEIGHT - GRID_ROWS * CHAR_H) / 2)   // ~8px  top  margin

// Buffer large enough for plain text rows plus LVGL recolor markup on dot rows.
// Worst case: 72 dots × "#RRGGBB o#" (10 bytes each) + row separators + header.
#define BUF_SIZE 800

// ── Colors ────────────────────────────────────────────────────────────────────
// 8 distinct colors cycled across completed-session dots; index wraps with % 8
static const uint32_t DOT_COLORS[8] = {
    0xFF6B6B, 0xFFD93D, 0x6BCB77, 0x4ECDC4,
    0x45B7D1, 0xF7B2BD, 0xC77DFF, 0xFFFFFF
};

// ── Font declaration ──────────────────────────────────────────────────────────
// Defined in departure_mono_upper_28.c (generated by lv_font_conv)
extern const lv_font_t departure_mono_upper_28;

// ── LVGL object ───────────────────────────────────────────────────────────────
// One label covers the entire grid; its text is rebuilt wholesale on every update
static lv_obj_t* mainLabel = nullptr;

// ── Screen state ──────────────────────────────────────────────────────────────
// Copies of the last values passed to updateTimer / updateTaskQueue.
// buildScreen() reads these to format the full string.
static int    s_secs     = 0;
static bool   s_running  = false;
static bool   s_waiting  = false;
static int    s_sessions = 0;
static char   s_phase[16] = "WORK";  // enough room for "WORK", "BREAK", "LONG REST"

static char   s_tasks[MAX_TASKS][TASK_MAX_LEN] = {};
static size_t s_count    = 0;
static size_t s_offset   = 0;
static size_t s_selected = 0;

static bool   s_sleeping = false;  // true while display is dimmed / sleeping

// ── Internal helpers ──────────────────────────────────────────────────────────

// Write a 12-char task row into dst (must have room for 13 bytes incl. null).
// num      — 1-based task number, prefix "N " or "NN "
// selected — appends '<' at column 12; name is truncated one char shorter to make room
static void fmtTaskRow(char* dst, int num, const char* name, bool selected) {
    char prefix[4];
    int plen   = snprintf(prefix, sizeof(prefix), "%d ", num);
    int budget = GRID_COLS - plen - (selected ? 1 : 0);  // chars available for name

    int namelen = (int)strlen(name);
    if (namelen > budget) namelen = budget;  // silent truncation

    memcpy(dst, prefix, plen);
    memcpy(dst + plen, name, namelen);

    // pad remaining columns with spaces so the row is always exactly GRID_COLS wide
    int filled = plen + namelen;
    int target = GRID_COLS - (selected ? 1 : 0);
    memset(dst + filled, ' ', target - filled);
    if (selected) dst[GRID_COLS - 1] = '<';
    dst[GRID_COLS] = '\0';
}

// Append colored dot markup to buf at *pos, up to maxDots dots.
// LVGL recolor format: "#RRGGBB text#" — the space after RRGGBB is a required separator,
// not a rendered character. Newline inserted after every GRID_COLS dots to wrap to next row.
static void appendDots(char* buf, int* pos, int count, int maxDots) {
    if (count > maxDots) count = maxDots;
    for (int i = 0; i < count; i++) {
        uint32_t c = DOT_COLORS[i % 8];
        *pos += snprintf(buf + *pos, BUF_SIZE - *pos, "#%06X O#", (unsigned int)c);
        if ((i + 1) % GRID_COLS == 0 && (i + 1) < count)
            buf[(*pos)++] = '\n';
    }
}

// Rebuild the full screen string from current state and push it to LVGL.
// Called by both updateTimer and updateTaskQueue so either change triggers a full redraw.
static void buildScreen() {
    static char buf[BUF_SIZE];
    int pos = 0;

    const bool isWork = (strcmp(s_phase, "WORK") == 0);
    const bool isLong = (strcmp(s_phase, "LONG REST") == 0);

    // ── Sleep screen: two centered rows (time + label), grid rows 3-4 ────────
    // Grid is 8 rows × 12 cols. Rows 0-2 blank, rows 3-4 content, rows 5-7 blank
    // gives 3 blank / 2 content / 3 blank — perfectly vertically centered.
    //
    // "   00:00   " → 3 + 5 + 4 = 12 chars (time centered in 12 cols)
    // "    WORK   " → 4 + 4 + 4 = 12 chars (4-char label centered)
    if (s_sleeping) {
        const char* sl;
        if (isWork)      sl = s_running ? "WORK" : (s_waiting ? "DONE" : "PAUSE");
        else if (isLong) sl = "LONG";
        else             sl = "REST";
        pos += snprintf(buf + pos, BUF_SIZE - pos,
                        "\n\n\n   %02d:%02d   \n    %-4s    \n",
                        s_secs / 60, s_secs % 60, sl);
        buf[pos] = '\0';
        lv_label_set_text(mainLabel, buf);
        return;
    }

    // ── Row 0: timer + phase label ────────────────────────────────────────────
    // work running → WORK, paused → PAUSE, expired → DONE
    // rest / long rest → BREAK / LONG (waiting state not shown separately)
    const char* label;
    if (isWork) {
        if      (s_running) label = "WORK";
        else if (s_waiting) label = "DONE";
        else                label = "PAUSE";
    } else {
        label = isLong ? "LONG" : "BREAK";
    }
    // "%-5s" pads label to 5 chars so the row is always 5+2+5 = 12 chars wide
    pos += snprintf(buf + pos, BUF_SIZE - pos, "%02d:%02d  %5s\n", s_secs/60, s_secs%60, label);

    // ── Rows 1+ depend on phase ───────────────────────────────────────────────
    if (isWork) {
        pos += snprintf(buf + pos, BUF_SIZE - pos, "\n");  // row 1: blank separator

        // rows 2-6: up to 5 task rows; blank row emitted when fewer tasks than rows
        for (int i = 0; i < GRID_ROWS - 3; i++) {
            size_t idx = s_offset + (size_t)i;
            if (idx < s_count) {
                char row[GRID_COLS + 1];
                fmtTaskRow(row, (int)(idx + 1), s_tasks[idx], (size_t)i == s_selected);
                pos += snprintf(buf + pos, BUF_SIZE - pos, "%s", row);
            }
            pos += snprintf(buf + pos, BUF_SIZE - pos, "\n");
        }
        // row 7: blank (end of grid)
    } else if (isLong) {
        pos += snprintf(buf + pos, BUF_SIZE - pos, "       BREAK\n");  // row 1: second label line
        pos += snprintf(buf + pos, BUF_SIZE - pos, "\n");              // row 2: blank
        // rows 3-7: 5 rows × 12 cols = 60 dots max
        appendDots(buf, &pos, s_sessions, (GRID_ROWS - 3) * GRID_COLS);
    } else {
        pos += snprintf(buf + pos, BUF_SIZE - pos, "\n");  // row 1: blank
        // rows 2-7: 6 rows × 12 cols = 72 dots max
        appendDots(buf, &pos, s_sessions, (GRID_ROWS - 2) * GRID_COLS);
    }

    buf[pos] = '\0';
    lv_label_set_text(mainLabel, buf);
}

// ── Public API ────────────────────────────────────────────────────────────────

void createUI(void) {
    lv_obj_t* scr = lv_scr_act();
    lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

    mainLabel = lv_label_create(scr);
    lv_label_set_recolor(mainLabel, true);  // enables #RRGGBB text# inline color markup
    lv_obj_set_style_text_font(mainLabel, &departure_mono_upper_28, 0);
    lv_obj_set_style_text_color(mainLabel, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_pos(mainLabel, BOX_X, BOX_Y);
    lv_label_set_long_mode(mainLabel, LV_LABEL_LONG_CLIP);  // no wrap, no scroll
    lv_obj_set_size(mainLabel, GRID_COLS * CHAR_W, GRID_ROWS * CHAR_H);
}

void updateTimer(int remainingSecs, const char* phase, bool running,
                 bool waitingContinue, int completedSessions) {
    s_secs     = remainingSecs;
    s_running  = running;
    s_waiting  = waitingContinue;
    s_sessions = completedSessions;
    strncpy(s_phase, phase, sizeof(s_phase) - 1);
    s_phase[sizeof(s_phase) - 1] = '\0';

    // Dark backgrounds keep most pixels off, reducing image retention.
    // Work: near-black + warm white text. Rest: dark green tint + cool white text.
    bool isWork = (strcmp(phase,"WORK") == 0);
    lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(isWork ? 0xFF8A00 : 0x0088D7), 0);
    lv_obj_set_style_text_color(mainLabel,  lv_color_hex(isWork ? 0x000000 : 0xEEEEEE), 0);

    buildScreen();
}

void updateTaskQueue(const char tasks[][TASK_MAX_LEN], size_t count,
                     size_t offset, size_t selected) {
    memcpy(s_tasks, tasks, count * TASK_MAX_LEN);
    s_count    = count;
    s_offset   = offset;
    s_selected = selected;
    buildScreen();
}

void setSleepMode(bool sleeping) {
    s_sleeping = sleeping;
    buildScreen();  // re-render immediately to show/hide the task list
}

void shiftPixels() {
    // 4-step cycle: corners of a 2×2 px square.
    // Each step moves the entire label slightly so no pixel holds the same
    // colour indefinitely — distributes voltage stress across neighbours.
    static const int8_t ox[4] = {0, 2, 2, 0};
    static const int8_t oy[4] = {0, 0, 2, 2};
    static uint8_t step = 0;
    step = (step + 1) % 4;
    lv_obj_set_pos(mainLabel, BOX_X + ox[step], BOX_Y + oy[step]);
}
